### PR TITLE
Improve error Information

### PR DESCRIPTION
**Pull request by naoto0822**
I have included the information needed to contact Apple in the error message.

1. x-b3-traceid header
Required on Apple form.
image

```go
traceID := resp.Header.Get("x-b3-traceid")
return 0, "", fmt.Errorf("http: %w: x-b3-traceid: %s", err, traceID)
```

2. full response
I added full response because it seems that they generally want full response information in addition to transaction_id, device_token etc.

```go
return fmt.Errorf("devicecheck: failed to query two bits: %w: %s", err, respBody)
```

### CODE REVIEW

**Comment by naoto0822** [comment]
@rinchsan 
Please kindly review 🙏

**Review by rinchsan — APPROVED** [review]
Looks good to me.
Thank you for your changes!

**Comment by naoto0822** [comment]
@rinchsan 
I can't seem to merge.
May I ask you to check the CI settings?

**Comment by rinchsan** [comment]
@naoto0822 
Sorry for my late actions.
I have just rolled out the new release with go version upgrade.
Could you kindly merge latest main branch to your branch, or rebase your branch from the latest main branch, so that we can wait for the CI check of this PR to be success for safety?

**Comment by naoto0822** [comment]
@rinchsan 
Thank you for your response.
I merged the main branch and CI passed, please confirm.

**Comment by rinchsan** [comment]
@naoto0822 
Thank you for merging the latest main branch.
It seems that some lint failures occurred, but I'm going to take care of these when releasing your changes in a new version.

**Pull request merged**
